[package]
name = "demo"
version = "0.1.0"
authors = ["Lauri Gustafsson <me@gustafla.space>"]
edition = "2018"

[features]
default = ["glutin"]
rpi = ["rpi_window", "khronos-egl"]

[dependencies]
# Optional, for different platforms
glutin = { version = "0.26.0", optional = true }
rpi_window =  { git = "https://github.com/gustafla/rpi_window", optional = true }
khronos-egl = { git = "https://github.com/gustafla/khronos-egl", optional = true, features = ["static", "no-pkg-config"] }

# Main dependencies
log = { version = "0.4.14", features = ["release_max_level_info"] }
rand = "0.8.3"
rand_xorshift = "0.3.0"
num_cpus = "1.13.0"
anyhow = "1.0.40"
thiserror = "1.0.24"
lewton = "0.10.2"
bincode = "1.3.3"
rust-rocket = "0.7.2"
glam = "0.14.0"
rustfft = "6.0.0"
pico-args = "0.4.1"
alsa = "0.5.0"

[build-dependencies]
gl_generator = "0.14.0"
pkg-config = "0.3.19"

[profile.dev]
opt-level = 2

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
