[package]
name = "demo"
version = "0.1.0"
authors = ["Lauri Gustafsson <me@gustafla.space>"]
edition = "2018"

[dependencies]
opengles = { git = "https://github.com/gustafla/rust-opengles" }
log = { version = "0.4", features = ["release_max_level_warn"] }
simple_logger = { version = "1.3.0", default-features = false }

[lib]
crate-type = ["cdylib"]
