[package]
name = "demo"
version = "0.1.0"
authors = ["Lauri Gustafsson <me@gustafla.space>"]
edition = "2018"

[dependencies]
log = { version = "0.4.13", features = ["release_max_level_info"] }
simple_logger = { version = "1.11.0", default-features = false }
rand = "0.8.2"
rand_xorshift = "0.3.0"
cgmath = { version = "0.18.0", default-features = false }
num_cpus = "1.13.0"
anyhow = "1.0.38"
glutin = "0.26.0"
thiserror = "1.0.23"
lewton = "0.10.1"
cpal = { git = "https://github.com/RustAudio/cpal" }
parking_lot = "0.11.1"
rust-rocket = { git = "https://github.com/Darksecond/rust-rocket" }
bincode = "1.3.1"

[build-dependencies]
gl_generator = "0.14.0"

[profile.dev]
opt-level = 2

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
