[package]
name = "demo"
version = "0.1.0"
authors = ["Lauri Gustafsson <me@gustafla.space>"]
edition = "2018"

[dependencies]
log = { version = "0.4.8", features = ["release_max_level_info"] }
simple_logger = { version = "1.6.0", default-features = false }
rand = "0.7.3"
rand_xorshift = "0.2.0"
cgmath = { version = "0.17.0", default-features = false }
num_cpus = "1.13.0"

[build-dependencies]
gl_generator = "0.14.0"

[lib]
crate-type = ["cdylib"]

[profile.dev]
opt-level = 3
