[package]
name = "demo"
version = "0.1.0"
authors = ["Lauri Gustafsson <me@gustafla.space>"]
edition = "2021"

[dependencies]
log = { version = "0.4.17", features = ["release_max_level_info"] }
anyhow = "1.0.58"
thiserror = "1.0.31"
lewton = "0.10.2"
bincode = "1.3.3"
rust-rocket = "0.7.2"
rustfft = "6.0.1"
pico-args = "0.5.0"
alsa = "0.6.0"
glam = "0.21.2"
winit = "0.26.1"

[profile.dev]
opt-level = 1

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
