[package]
name = "demo"
version = "0.1.0"
authors = ["Lauri Gustafsson <me@gustafla.space>"]
edition = "2021"

[dependencies]
glutin = "0.27.0"
log = { version = "0.4.14", features = ["release_max_level_info"] }
rand = "0.8.4"
rand_xorshift = "0.3.0"
anyhow = "1.0.44"
thiserror = "1.0.29"
lewton = "0.10.2"
bincode = "1.3.3"
rust-rocket = "0.7.2"
rustfft = "6.0.1"
pico-args = "0.4.2"
alsa = "0.5.0"

[build-dependencies]
gl_generator = "0.14.0"
pkg-config = "0.3.20"

[profile.dev]
opt-level = 1

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
