[package]
name = "demo"
version = "0.1.0"
authors = ["Lauri Gustafsson <me@gustafla.space>"]
edition = "2018"

[dependencies]
log = { version = "0.4.14", features = ["release_max_level_info"] }
rand = "0.8.3"
rand_xorshift = "0.3.0"
num_cpus = "1.13.0"
anyhow = "1.0.38"
glutin = "0.26.0"
thiserror = "1.0.23"
lewton = "0.10.2"
bincode = "1.3.1"
rust-rocket = "0.7.2"
glam = "0.12.0"
rustfft = "5.0.1"
pulse_simple = { package = "libpulse-simple-binding", version = "2.23.0" }
pulse = { package = "libpulse-binding", version = "2.23.0" }
pico-args = "0.4.0"

[build-dependencies]
gl_generator = "0.14.0"

[profile.dev]
opt-level = 2

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
