FROM liuchong/rustup:stable

# Install required setup tools
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    git cmake intltool wget pkg-config && \
    rm -rf /var/lib/apt/lists/*

# Install the RPi toolchain
RUN git clone --depth 1 https://github.com/raspberrypi/tools && \
cp -r tools/arm-bcm2708/arm-linux-gnueabihf/* /usr && rm -r ~/*

# Install the RPi GPU driver userland
RUN git clone --depth 1 https://github.com/raspberrypi/userland && \
cd userland && \
./buildme && \
cd build/arm-linux/release && \
make install && \
cd && rm -r ~/*

# Install alsa
RUN wget ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.1.8.tar.bz2 && \
tar xf alsa-lib-1.1.8.tar.bz2 && cd alsa-lib-1.1.8 && \
./configure --prefix /usr/arm-linux-gnueabihf --host arm-linux-gnueabihf && \
make -j $(nproc) && make install && cd && rm -r ~/*

# Install Rust target arm-unknown-linux-gnueabihf
RUN rustup target add arm-unknown-linux-gnueabihf
RUN printf '[target.arm-unknown-linux-gnueabihf]\nlinker = "arm-linux-gnueabihf-gcc"' > /root/.cargo/config.toml

# Setup pkg-config-rs
ENV PKG_CONFIG_PATH=/usr/arm-linux-gnueabihf/lib/pkgconfig:/opt/vc/lib/pkgconfig
ENV PKG_CONFIG_ALLOW_CROSS=1
