FROM liuchong/rustup:stable
RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install --no-install-recommends -y \
    gcc-arm-linux-gnueabihf libgles2-mesa-dev:armhf libpulse-dev:armhf && \
    rm -rf /var/lib/apt/lists/*
RUN rustup target add arm-unknown-linux-gnueabihf
RUN printf '[target.arm-unknown-linux-gnueabihf]\nlinker = "arm-linux-gnueabihf-gcc"' > /root/.cargo/config.toml
ENV PKG_CONFIG=arm-linux-gnueabihf-pkg-config
ENV PKG_CONFIG_LIBDIR_arm_unknown_linux_gnueabihf=/usr/lib/arm-linux-gnueabihf/pkgconfig
